spring:
  datasource:
    url: jdbc:h2:file:./camunda-loan-agreement-h2-database
  jpa:
    hibernate:
      ddl-auto: create-drop

camunda.bpm.admin-user:
  id: admin
  password: pw
  generic-properties:
    properties:
      initializeTelemetry: false