spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

camunda.bpm.admin-user:
  id: admin
  password: pw
  generic-properties:
    properties:
      initializeTelemetry: false